apiVersion: v1
kind: Service
metadata:
  name: sentry-web
  namespace: sentry
spec:
  ports:
  - port: 80 
    targetPort: 9000
    protocol: TCP
  type: NodePort
  selector:
    app: sentry-onpremise
